# Generated by Django 2.2.17 on 2021-06-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('datetime', models.DateField()),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('gps_alt', models.IntegerField()),
                ('pm1', models.IntegerField()),
                ('pm10', models.IntegerField()),
                ('pm2_5', models.IntegerField()),
                ('airpressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
