# Generated by Django 2.2.17 on 2021-06-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
